export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const SET_SELECTED_BOOTH = "SET_SELECTED_BOOTH"
export const CLEAR_SELECTED_BOOTH = "CLEAR_SELECTED_BOOTH"

export const ADD_REVIEW = "ADD_REVIEW"
export const REVIEW_LOADING = "REVIEW_LOADING"
export const REVIEW_LOADED = "REVIEW_LOADED"

export const FAVORITE_BOOTH = "FAVORITE_BOOTH"